kind: pipeline
name: test

steps:
- name: Install
  image: node
  commands:
  - npm install

- name: Something else
  image: node
  commands:
    - ls

- name: Test
  image: node
  commands:
  - npm test
